### PR TITLE
functests: Drop Ginkgo dependency

### PR DESCRIPTION
**Pull request by wking**
Use Go's built-in testing package instead.  This avoids issues [like][1]:

```
Retrieving ginkgo and gomega build dependencies
go: github.com/openshift/cluster-image-registry-operator@v0.0.0-20200415091009-99c06ee64540 requires
		github.com/openshift/library-go@v0.0.0-20200327125526-163b2f0d6264 requires
		bitbucket.org/ww/goautoneg@v0.0.0-20120707110453-75cd24fc2f2c: reading https://api.bitbucket.org/2.0/repositories/ww/goautoneg?fields=scm: 404 Not Found
go: github.com/openshift/cluster-image-registry-operator@v0.0.0-20200415091009-99c06ee64540 requires
		github.com/openshift/library-go@v0.0.0-20200327125526-163b2f0d6264 requires
		bitbucket.org/ww/goautoneg@v0.0.0-20120707110453-75cd24fc2f2c: reading https://api.bitbucket.org/2.0/repositories/ww/goautoneg?fields=scm: 404 Not Found
hack/functest.sh: line 17: /go/bin/ginkgo: No such file or directory
hack/functest.sh: line 19: /go/bin/ginkgo: No such file or directory
```

The tests are simple enough that Ginkgo structuring was overkill anyway.  Generated by manually editing files in `functests`, and then running:

```console
$ go mod tidy
$ go mod vendor
$ git add -A go.* vendor
```

using:

```console
$ go version
go version go1.15.2 linux/amd64
```

[1]: https://github.com/openshift/cincinnati-operator/pull/66#issuecomment-703931608

### CODE REVIEW

**Comment by wking** [comment]
[e2e][1]:

```
I1019 23:14:32.267387    4738 utils.go:121] Waiting for full availability of cincinnati-operator deployment (0/1)
panic: test timed out after 10m0s
```

Because:

```console
$ curl -s https://gcsweb-ci.apps.ci.l2s4.p1.openshiftapps.com/gcs/origin-ci-test/pr-logs/pull/openshift_cincinnati-operator/69/pull-ci-openshift-cincinnati-operator-master-cincinnati-operator-e2e-aws/1318318319090012160/artifacts/cincinnati-operator-e2e-aws/pods.json | jq -r '.items[] | select(.metadata.name | startswith("cincinnati-operator-")).status.containerStatuses[].state'
{
  "waiting": {
    "message": "Back-off pulling image \"registry.svc.ci.openshift.org/ci-op-9s6krr21/stable:cincinnati-operator\"",
    "reason": "ImagePullBackOff"
  }
}
```

Dunno what to do about that...

[1]: https://prow.ci.openshift.org/view/gs/origin-ci-test/pr-logs/pull/openshift_cincinnati-operator/69/pull-ci-openshift-cincinnati-operator-master-cincinnati-operator-e2e-aws/1318318319090012160

**Comment by jottofar** [comment]
You're where I'm at now I believe.

https://gcsweb-ci.apps.ci.l2s4.p1.openshiftapps.com/gcs/origin-ci-test/pr-logs/pull/openshift_cincinnati-operator/69/pull-ci-openshift-cincinnati-operator-master-cincinnati-operator-e2e-aws/1318318319090012160/artifacts/cincinnati-operator-e2e-aws/events.json:
"message": "Back-off pulling image \"registry.svc.ci.openshift.org/ci-op-9s6krr21/stable:cincinnati-operator\""

Which according to our thread https://coreos.slack.com/archives/CBN38N3MW/p1603125539363800 is due to a need to use `dependencies` and therefore a need to get your multi-step PR merged.

**Comment by wking** [comment]
I'm more confident in this change vs. the release one.  Can we `/override ...` here to get the more meaningful rehearsals there?

**Comment by wking** [comment]
/override ci/prow/cincinnati-operator-e2e-aws

Assume this is ok, so we can work on rehearsals in openshift/release#12486.

**Pull request merged**
