### PR TITLE
OCPBUGS-12485: Bump `golang.org/x/net` to v0.7.0

### PR DESCRIPTION
**Pull request by petr-muller**
```
$ go get -u golang.org/x/net@v0.7.0
go: upgraded golang.org/x/net v0.0.0-20220722155237-a158d28d115b => v0.7.0
go: upgraded golang.org/x/sys v0.0.0-20220722155257-8c9f86f7a55f => v0.5.0
go: upgraded golang.org/x/term v0.0.0-20210927222741-03fcf44c2211 => v0.5.0
go: upgraded golang.org/x/text v0.3.7 => v0.7.0
$ go mod tidy
$ go mod vendor
```

### CODE REVIEW

**Comment by petr-muller** [comment]
/hold
Both jobs should not fail afaik, will investigate

**Comment by petr-muller** [comment]
/override ci/prow/operator-e2e
([permafails](https://prow.ci.openshift.org/job-history/gs/origin-ci-test/pr-logs/directory/pull-ci-openshift-cincinnati-operator-master-operator-e2e)): I do not remember the reason though.

/test operator-e2e-latest-osus
The run seems a bit unlucky, the 10m wait ended on `16:07:34.845476` but the Deployment only went all-ready on `2023-04-28T16:08:05Z`

I also found out that we only test the operator on 4.10 and the tests (not the operator) are actually broken on OCP 4.12+. I am toying with extending the coverage in https://github.com/openshift/release/pull/39394

**Review by PratikMahajan — APPROVED** [review]
/lgtm

**Comment by petr-muller** [comment]
/hold 

https://github.com/openshift/release/pull/39431 should fix the job, we can as well wait for it

**Pull request merged**
