### PR TITLE
Deleting the olm-catalog CSV files.

### PR DESCRIPTION
**Pull request by LalatenduMohanty**
As we do not use these anywhere and these are not uptodate.

Signed-off-by: Lalatendu Mohanty <lmohanty@redhat.com>

### CODE REVIEW

**Review by PratikMahajan — APPROVED** [review]
/lgtm
/hold for @vrutkovs and @wking to review.

**Comment by jottofar** [comment]
That entire directory `olm-catalog` can be removed.

**Review by wking — APPROVED** [review]
/lgtm

**Pull request merged**
