### PR TITLE
add PratikMahajan as owner and reviewer for cincinnati operator

### PR DESCRIPTION
**Pull request by PratikMahajan**

### CODE REVIEW

**Review by wking — APPROVED** [review]
/lgtm

**Comment by PratikMahajan** [comment]
we need to override `operator-e2e` as it has a pinned commit that does not include multi-arch support. cc @jottofar

**Comment by jottofar** [comment]
/override ci/prow/operator-e2e

operator-e2e is pinned to a specific commit which does not contain the fix for sha-sum mismatch.
ci/prow/operator-e2e-latest-osus uses the latest commit from cincinnati and has passed the tests.

**Pull request merged**
