### PR TITLE
Bumping the go version to 1.18

### PR DESCRIPTION
**Pull request by LalatenduMohanty**
Steps:
* edit the go.mod file
* go mod tidy
* go mod vendor

Signed-off-by: Lalatendu Mohanty <lmohanty@redhat.com>

### CODE REVIEW

**Review by wking — APPROVED** [review]
/lgtm

**Review by PratikMahajan — APPROVED** [review]
/lgtm

**Comment by LalatenduMohanty** [comment]
Test failed with below error https://prow.ci.openshift.org/view/gs/origin-ci-test/pr-logs/pull/openshift_cincinnati-operator/155/pull-ci-openshift-cincinnati-operator-master-operator-e2e/1612885365167755264

```
{  "operator-e2e" test steps failed: "operator-e2e" pod "operator-e2e-e2e-test" failed: the pod ci-op-bc8pbr8n/operator-e2e-e2e-test failed after 12m15s (failed containers: test): ContainerFailed one or more containers exited

Container test exited with code 1, reason Error
---
] Waiting for full availability of example deployment (0/1)
I0110 19:00:49.199595    5173 utils.go:106] Waiting for full availability of example deployment (0/1)
I0110 19:01:19.196637    5173 utils.go:106] Waiting for full availability of example deployment (0/1)
I0110 19:01:49.197912    5173 utils.go:106] Waiting for full availability of example deployment (0/1)
I0110 19:02:19.199722    5173 utils.go:106] Waiting for full availability of example deployment (0/1)
I0110 19:02:49.201395    5173 utils.go:106] Waiting for full availability of example deployment (0/1)
I0110 19:03:19.198208    5173 utils.go:106] Waiting for full availability of example deployment (0/1)
I0110 19:03:49.199284    5173 utils.go:106] Waiting for full availability of example deployment (0/1)
I0110 19:04:19.199446    5173 utils.go:106] Waiting for full availability of example deployment (0/1)
I0110 19:04:49.198505    5173 utils.go:106] Waiting for full availability of example deployment (0/1)
I0110 19:05:19.199708    5173 utils.go:106] Waiting for full availability of example deployment (0/1)
I0110 19:05:49.199079    5173 utils.go:106] Waiting for full availability of example deployment (0/1)
I0110 19:06:19.197931    5173 utils.go:106] Waiting for full availability of example deployment (0/1)
I0110 19:06:49.200328    5173 utils.go:106] Waiting for full availability of example deployment (0/1)
I0110 19:06:49.223250    5173 utils.go:106] Waiting for full availability of example deployment (0/1)
    updateservice_creation_test.go:74: timed out waiting for the condition
--- FAIL: TestCustomResource (662.48s)
FAIL
FAIL	github.com/openshift/cincinnati-operator/functests	662.497s
FAIL
make: *** [func-test] Error 1
{"component":"entrypoint","error":"wrapped process failed: exit status 2","file":"k8s.io/test-infra/prow/entrypoint/run.go:79","func":"k8s.io/test-infra/prow/entrypoint.Options.Run","level":"error","msg":"Error executing test process","severity":"error","time":"2023-01-10T19:06:49Z"}
error: failed to execute wrapped command: exit status 2
---
Link to step on registry info site: https://steps.ci.openshift.org/reference/e2e-test
Link to job on registry info site: https://steps.ci.openshift.org/job?org=openshift&repo=cincinnati-operator&branch=master&test=operator-e2e}
```

**Comment by petr-muller** [comment]
Nothing indicative in the gathered artifacts, the pod just never goes ready in ~13m (since starting the test until `gather-extra`):

```json
    {
      "lastProbeTime": null,
      "lastTransitionTime": "2023-01-10T19:35:48Z",
      "message": "containers with unready status: [graph-builder]",
      "reason": "ContainersNotReady",
      "status": "False",
      "type": "Ready"
    },
[events.json.txt](https://github.com/openshift/cincinnati-operator/files/10392760/events.json.txt)
[podstatus.json.txt](https://github.com/openshift/cincinnati-operator/files/10392761/podstatus.json.txt)

    {
      "lastProbeTime": null,
      "lastTransitionTime": "2023-01-10T19:35:48Z",
      "message": "containers with unready status: [graph-builder]",
      "reason": "ContainersNotReady",
      "status": "False",
      "type": "ContainersReady"
    },
```

Nothing that useful in events either, just 503 from ready endpoint:

```json
{
  "apiVersion": "v1",
  "count": 67,
  "eventTime": null,
  "firstTimestamp": "2023-01-10T19:36:08Z",
  "involvedObject": {
    "apiVersion": "v1",
    "fieldPath": "spec.containers{graph-builder}",
    "kind": "Pod",
    "name": "example-6b555598b8-67zv5",
    "namespace": "openshift-updateservice",
    "resourceVersion": "90525",
    "uid": "043dc78a-3665-411b-bf4c-218e83528125"
  },
  "kind": "Event",
  "lastTimestamp": "2023-01-10T19:45:58Z",
  "message": "Readiness probe error: HTTP probe failed with statuscode: 503\nbody: \n",
  "metadata": {
    "creationTimestamp": "2023-01-10T19:36:08Z",
    "name": "example-6b555598b8-67zv5.173909ab8e936870",
    "namespace": "openshift-updateservice",
    "resourceVersion": "93750",
    "uid": "66f5978a-67fc-4101-a28a-a4568a6c2670"
  },
  "reason": "ProbeError",
  "reportingComponent": "",
  "reportingInstance": "",
  "source": {
    "component": "kubelet",
    "host": "ip-10-0-145-132.us-west-1.compute.internal"
  },
  "type": "Warning"
}
```

**Comment by petr-muller** [comment]
Is it possible that we added readiness probes in https://github.com/openshift/cincinnati/pull/740 and now our tests fail because the container stands up too slowly?

**Review by PratikMahajan — COMMENTED** [review]
/override ci/prow/operator-e2e

Test fails as cincinnati does not have the manifest-ref bugfix. 
`ci/prow/operator-e2e-latest-osus` is same test with latest version of cincinnati

**Pull request merged**
