### PR TITLE
Upgrade OSUS Operator to SDK v1.9.0

### PR DESCRIPTION
**Pull request by jottofar**
Steps:

- Create new branch
- remove *
- Use operator-sdk v1.9.0
- Use  controller-gen version >= v0.4.1

$ operator-sdk version
operator-sdk version: "v1.9.0", commit: "205e0a0c2df0715d133fbe2741db382c9c75a341", kubernetes version: "1.20.2", go version: "go1.16.5", GOOS: "linux", GOARCH: "amd64"

$ operator-sdk init --domain openshift.io --project-name update-service-operator --repo github.com/openshift/cincinnati-operator
Writing kustomize manifests for you to edit...
Writing scaffold for you to edit...
Get controller runtime:
$ go get sigs.k8s.io/controller-runtime@v0.8.3
Update dependencies:
$ go mod tidy
Next: define a resource with:
$ operator-sdk create api

$ ls
config  Dockerfile  go.mod  go.sum  hack  main.go  Makefile  PROJECT

$ operator-sdk create api --group updateservice.operator --version v1 --kind UpdateService --resource --controller
Writing kustomize manifests for you to edit...
Writing scaffold for you to edit...
api/v2/updateservice_types.go
controllers/updateservice_controller.go
Update dependencies:
$ go mod tidy
Running make:
$ make generate
go: creating new go.mod: module tmp
Downloading sigs.k8s.io/controller-tools/cmd/controller-gen@v0.4.1
go get: added sigs.k8s.io/controller-tools v0.4.1
/home/jottofar/go/src/github.com/openshift/cincinnati-operator/bin/controller-gen object:headerFile="hack/boilerplate.go.txt" paths="./..."
$ ls
api  bin  config  controllers  Dockerfile  go.mod  go.sum  hack  main.go  Makefile  PROJECT

$ git restore Dockerfile LICENSE OWNERS README.md build hack/deploy.sh vendor Makefile dev/Dockerfile docs functests tools version

$ git status
On branch upgrade-to-v1.9.0
Changes not staged for commit:
  (use "git add/rm <file>..." to update what will be committed)
  (use "git restore <file>..." to discard changes in working directory)
	modified:   PROJECT
	modified:   api/v1/groupversion_info.go
	modified:   api/v1/updateservice_types.go
	modified:   api/v1/zz_generated.deepcopy.go
	deleted:    config/certmanager/certificate.yaml
	deleted:    config/certmanager/kustomization.yaml
	deleted:    config/certmanager/kustomizeconfig.yaml
	deleted:    config/crd/bases/updateservice.operator.openshift.io_updateservices.yaml
	modified:   config/crd/kustomization.yaml
	modified:   config/crd/kustomizeconfig.yaml
	modified:   config/crd/patches/cainjection_in_updateservices.yaml
	modified:   config/crd/patches/webhook_in_updateservices.yaml
	modified:   config/default/kustomization.yaml
	deleted:    config/default/manager_webhook_patch.yaml
	deleted:    config/default/webhookcainjection_patch.yaml
	modified:   config/manager/kustomization.yaml
	modified:   config/manager/manager.yaml
	deleted:    config/manifests/bases/update-service-operator.clusterserviceversion.yaml
	modified:   config/manifests/kustomization.yaml
	modified:   config/prometheus/monitor.yaml
	modified:   config/rbac/auth_proxy_client_clusterrole.yaml
	modified:   config/rbac/auth_proxy_role.yaml
	modified:   config/rbac/auth_proxy_role_binding.yaml
	modified:   config/rbac/auth_proxy_service.yaml
	modified:   config/rbac/kustomization.yaml
	modified:   config/rbac/leader_election_role.yaml
	modified:   config/rbac/leader_election_role_binding.yaml
	deleted:    config/rbac/role.yaml
	modified:   config/rbac/role_binding.yaml
	modified:   config/rbac/service_account.yaml
	modified:   config/samples/kustomization.yaml
	deleted:    config/samples/updateservice.operator.openshift.io_v1_updateservice_cr.yaml
	modified:   config/samples/updateservice.operator_v1_updateservice.yaml
	modified:   config/scorecard/kustomization.yaml
	modified:   config/scorecard/patches/basic.config.yaml
	modified:   config/scorecard/patches/olm.config.yaml
	deleted:    config/webhook/kustomization.yaml
	deleted:    config/webhook/kustomizeconfig.yaml
	deleted:    config/webhook/service.yaml
	deleted:    controllers/controller.go
	deleted:    controllers/mapper.go
	deleted:    controllers/mapper_test.go
	deleted:    controllers/names.go
	deleted:    controllers/new.go
	modified:   controllers/updateservice_controller.go
	deleted:    controllers/updateservice_controller_test.go
	modified:   go.mod
	modified:   go.sum
	modified:   main.go

Untracked files:
  (use "git add <file>..." to include in what will be committed)
	.dockerignore
	bin/
	config/default/manager_auth_proxy_patch.yaml
	config/default/manager_config_patch.yaml
	config/manager/controller_manager_config.yaml
	controllers/suite_test.go
	hack/boilerplate.go.txt

$ git restore api/v1/groupversion_info.go
$ git restore api/v1/updateservice_types.go (edited)
$ git restore api/v1/zz_generated.deepcopy.go
$ git add config/crd/kustomization.yaml
$ git add config/crd/kustomizeconfig.yaml 
$ git add config/crd/patches/cainjection_in_updateservices.yaml
$ git add config/crd/patches/webhook_in_updateservices.yaml
$ git restore config/default/kustomization.yaml
$ vi config/default/kustomization.yaml
$ git add config/default/kustomization.yaml
$ git add config/manager/kustomization.yaml
$ git restore config/manager/manager.yaml
$ vi config/manager/manager.yaml
$ git status
$ git restore config/manifests/kustomization.yaml
$ git restore config/manifests/bases/update-service-operator.clusterserviceversion.yaml

$ git restore config/prometheus/monitor.yaml
$ git add config/rbac/auth_proxy_client_clusterrole.yaml
$ git add config/rbac/auth_proxy_role.yaml
$ git add config/rbac/auth_proxy_role_binding.yaml
$ git restore config/rbac/auth_proxy_service.yaml
$ git add config/rbac/kustomization.yaml
$ git add config/rbac/leader_election_role.yaml
$ git add config/rbac/leader_election_role_binding.yaml
$ git restore config/rbac/role.yaml (was deleted)
$ git restore config/rbac/role_binding.yaml
$ git restore config/rbac/service_account.yaml
$ git add config/samples/kustomization.yaml
$ git restore config/samples/updateservice.operator.openshift.io_v1_updateservice_cr.yaml (was deleted)
$ git restore config/samples/updateservice.operator_v1_updateservice.yaml
$ git add config/scorecard/kustomization.yaml
$ git add config/scorecard/patches/basic.config.yaml
$ git add config/scorecard/patches/olm.config.yaml
$ git add config/webhook/kustomization.yaml config/webhook/kustomizeconfig.yaml config/webhook/service.yaml
$ git restore controllers/controller.go controllers/mapper.go controllers/mapper_test.go controllers/names.go controllers/new.go controllers/updateservice_controller_test.go
$ git restore controllers/updateservice_controller.go
$ vi controllers/updateservice_controller.go
$ git add controllers/updateservice_controller.go
$ git restore main.go
$ vi main.go
$ git add main.go
$ rm .dockerignore
$ rm -rf bin
$ rm config/manager/controller_manager_config.yaml
$ rm controllers/suite_test.go
$ rm hack/boilerplate.go.txt

-- modified config/crd/bases/updateservice.operator.openshift.io_updateservices.yaml to remove metadat from openAPIV3Schema per spec change.

-- generate manifests (creates config/crd/bases/updateservice.operator.openshift.io_updateservices.yaml)
$ make manifests

-- generate config/manifests/bases/update-service-operator.clusterserviceversion.yaml and
-- compare to basline for updates (builder and project_layout version updates)
$ operator-sdk generate kustomize manifests

Module changes:
- go.mod updates from SDK doc per latest (v1.7.0) guidance
- changed go to 1.16

...
module github.com/openshift/cincinnati-operator

go 1.16

require (
        k8s.io/api v0.20.2
        k8s.io/apimachinery v0.20.2
        k8s.io/client-go v0.20.2
        k8s.io/klog v1.0.0
        k8s.io/kubectl v0.20.2
        sigs.k8s.io/controller-runtime v0.8.3
)  
...
$ go mod tidy
...
go: finding module for package github.com/openshift/api/config/v1
github.com/openshift/cincinnati-operator imports
	github.com/openshift/api/config/v1: module github.com/openshift/api@latest found (v3.9.0+incompatible), but does not contain package github.com/openshift/api/config/v1
github.com/openshift/cincinnati-operator/functests imports
	k8s.io/kubectl/pkg/scheme imports
	k8s.io/api/batch/v2alpha1: module k8s.io/api@latest found (v0.22.1), but does not contain package k8s.io/api/batch/v2alpha1

-- modified go.mod
...
module github.com/openshift/cincinnati-operator

go 1.16

require (
        github.com/go-logr/logr v0.4.0
        github.com/openshift/api v0.0.0-20210907084939-33af3ff57ff1
        github.com/openshift/cluster-image-registry-operator v0.0.0-20210830135433-48485bb2206c
        github.com/openshift/custom-resource-status v1.1.0
        github.com/openshift/library-go v0.0.0-20210906100234-6754cfd64cb5
        github.com/stretchr/testify v1.7.0
        k8s.io/api v0.22.1
        k8s.io/apimachinery v0.22.1
        k8s.io/client-go v0.22.1
        k8s.io/kubectl v0.22.1
        sigs.k8s.io/controller-runtime v0.8.3
)

exclude github.com/openshift/api v3.9.0+incompatible

replace (
        k8s.io/api v0.22.1 => k8s.io/api v0.20.2
        k8s.io/apimachinery v0.22.1 => k8s.io/apimachinery v0.20.2
        k8s.io/client-go v0.22.1 => k8s.io/client-go v0.20.2
        k8s.io/kubectl v0.22.1 => k8s.io/kubectl v0.20.2
)
...
$ go mod tidy
$ go mod vendor

### CODE REVIEW

**Comment by jottofar** [comment]
/retitle WIP: Upgraded OSUS Operator to SDK v1.9.0

**Comment by jottofar** [comment]
/retitle WIP: Upgrade OSUS Operator to SDK v1.9.0

**Comment by jottofar** [comment]
/retitle Upgrade OSUS Operator to SDK v1.9.0

**Comment by jottofar** [comment]
Going to test one more time before merging.

/hold

**Review by wking — APPROVED** [review]
Maybe Prow was asleep?

/lgtm

**Pull request merged**
